# Generated by Django 3.0.8 on 2020-07-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200706_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='desc',
        ),
        migrations.AddField(
            model_name='classes',
            name='classes',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='teacher',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classes',
            name='subject',
            field=models.CharField(max_length=30),
        ),
    ]
