# Generated by Django 3.0.8 on 2020-07-06 12:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200706_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
