# Generated by Django 3.0.8 on 2020-07-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200706_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='created_at',
        ),
    ]
