# Generated by Django 3.0.8 on 2020-07-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_classes_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.UUIDField(default='c9618b17', editable=False, primary_key=True, serialize=False),
        ),
    ]
