# Generated by Django 3.0.8 on 2020-07-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200706_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.CharField(default='ce2af717', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
