# Generated by Django 3.0.8 on 2020-07-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200706_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='code',
            field=models.CharField(default='2063', editable=False, max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
