# Generated by Django 3.0.8 on 2020-07-06 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200706_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='code',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
