# Generated by Django 3.0.8 on 2020-07-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200706_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
