# Generated by Django 3.0.8 on 2020-07-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200706_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='id',
        ),
        migrations.AlterField(
            model_name='classes',
            name='code',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
