# Generated by Django 3.0.8 on 2020-07-07 09:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_classes_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='join',
            unique_together={('class_code', 'user_id')},
        ),
    ]
