# Generated by Django 3.0.8 on 2020-07-09 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200707_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upoladingdate', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField(blank=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Classes')),
            ],
        ),
    ]
