# Generated by Django 3.0.8 on 2020-07-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
