# Generated by Django 3.0.8 on 2020-07-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200714_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='upoladingdate',
            new_name='uploadingdate',
        ),
        migrations.AlterField(
            model_name='notes',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
