# Generated by Django 3.0.8 on 2020-07-26 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200714_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadingdate', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField(blank=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('last_date', models.DateTimeField()),
                ('submitted_date', models.DateTimeField(null=True)),
                ('marks', models.FloatField(null=True)),
                ('max_marks', models.FloatField()),
                ('flag', models.BooleanField(default=False)),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Classes')),
            ],
        ),
    ]
