# Generated by Django 3.0.8 on 2020-07-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='remarks',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
