# Generated by Django 3.0.8 on 2020-07-27 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0021_assignment_submitted_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='submitted_date',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='submitted_file',
        ),
        migrations.CreateModel(
            name='SubmitAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_file', models.FileField(upload_to='')),
                ('submitted_date', models.DateTimeField()),
                ('marks', models.FloatField(null=True)),
                ('remarks', models.CharField(blank=True, max_length=40)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Assignment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
