# Generated by Django 3.0.8 on 2020-07-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200727_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitassignment',
            name='submitted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
