# Generated by Django 3.0.8 on 2020-07-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200727_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitassignment',
            name='remarks',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
